# Generated by Django 5.1 on 2024-08-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio_app.portfolio'),
        ),
    ]
