# Generated by Django 5.1 on 2024-08-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
